// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_2d7KeVS1Q9e10uMzP-Dy03UYF6HOqVI',
    appId: '1:528964631355:web:d706010ecbd7b9ecb3951e',
    messagingSenderId: '528964631355',
    projectId: 'test-firebase-c42cf',
    authDomain: 'test-firebase-c42cf.firebaseapp.com',
    storageBucket: 'test-firebase-c42cf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoXptUlSWBDNNVo1GVIgefxP3KXLDAWmU',
    appId: '1:528964631355:android:fb417d636b27028db3951e',
    messagingSenderId: '528964631355',
    projectId: 'test-firebase-c42cf',
    storageBucket: 'test-firebase-c42cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyw3kyYQZoCYK9O6L7WsDsw7dG_ilGv6Y',
    appId: '1:528964631355:ios:9c5efff5391877b5b3951e',
    messagingSenderId: '528964631355',
    projectId: 'test-firebase-c42cf',
    storageBucket: 'test-firebase-c42cf.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyw3kyYQZoCYK9O6L7WsDsw7dG_ilGv6Y',
    appId: '1:528964631355:ios:9c5efff5391877b5b3951e',
    messagingSenderId: '528964631355',
    projectId: 'test-firebase-c42cf',
    storageBucket: 'test-firebase-c42cf.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_2d7KeVS1Q9e10uMzP-Dy03UYF6HOqVI',
    appId: '1:528964631355:web:e8e9dc2f114bee9bb3951e',
    messagingSenderId: '528964631355',
    projectId: 'test-firebase-c42cf',
    authDomain: 'test-firebase-c42cf.firebaseapp.com',
    storageBucket: 'test-firebase-c42cf.firebasestorage.app',
  );
}